# Generated by Django 2.2 on 2020-02-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_auto_20200219_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
